In [1]:
import numpy as np

In [2]:
A=np.array([
    [1,1],
    [1,2],
    [1,3]
    ])

In [3]:
y = np.array([1,2,2])

In [4]:
#projection matrix
P=A@np.linalg.inv(A.T@A)@A.T

In [5]:
proj_y=P@y

In [6]:
print("Projection of y;",proj_y)

Projection of y; [1.16666667 1.66666667 2.16666667]


Intuition

In [7]:
A=np.array([
    [1,2],
    [0,1],
    [1,3]
])

In [8]:
# columns of A
a1=A[:,0]
a2=A[:,1]

In [9]:
a1

array([1, 0, 1])

In [10]:
a2

array([2, 1, 3])

In [11]:
# any vector in col(A) looks like:
# c1 * a1 + c2 * a2

min ||Aw-b||^2

In [12]:
A=np.array([
    [1,2],
    [1,2],
    [1,3]
])
b=np.array([1,2,2])

compute A^T A

In [13]:
ATA=A.T@A
print("A^T A = \n", ATA)

A^T A = 
 [[ 3  7]
 [ 7 17]]


In [14]:
ATb=A.T@b
print("A^T b = \n", ATb)

A^T b = 
 [ 5 12]


solve the normal equations
(A^T A)w = (A^T b)

In [15]:
w=np.linalg.inv(ATA)@ATb
print("Solution w=",w)

Solution w= [0.5 0.5]


alternatively (better numerically)

In [16]:
w=np.linalg.solve(ATA,ATb)

check the result

In [17]:
pred=A@w
print("predicted values =", pred)

predicted values = [1.5 1.5 2. ]


compute the residual

In [18]:
r=b-pred
print("Residuial =", r)

Residuial = [-5.0000000e-01  5.0000000e-01  8.8817842e-16]


check orthogonality A^T r = 0

In [19]:
print("A^T r =",A.T@r)

A^T r = [-4.4408921e-16  0.0000000e+00]


full script for least squares problem

In [20]:
import numpy as np

# data
A=np.array([
    [1,2],
    [1,2],
    [1,3]
])
b=np.array([1,2,2])

# step 1: form A^T A
ATA=A.T@A
print("A^T A=",ATA)

# step 2: form A^T b
ATb=A.T@b
print("A^T b=",ATb)

# step 3 solve normal equations (A^T A w = A^T b)
w=np.linalg.solve(ATA,ATb)
print("w=",w)

# step 4: check projection properties
pred=A@w
print("predicted values=",pred)

r=b-pred
print("residual=",r)

# check orthogonality: A^T r should be 0
print("A^T r=",A.T@r)
      
      

A^T A= [[ 3  7]
 [ 7 17]]
A^T b= [ 5 12]
w= [0.5 0.5]
predicted values= [1.5 1.5 2. ]
residual= [-5.0000000e-01  5.0000000e-01  8.8817842e-16]
A^T r= [-4.4408921e-16  0.0000000e+00]


vector valued function

In [21]:
def f(x):
    # x is a vector of lengtgh 2
    return np.array([
        x[0]**2,
        np.sin(x[1]),
        x[0]+x[1]
    ])

returns a vector valued function - a fuction whose output is a vector not a single number

In [22]:
print(f(np.array([2.0,1.0])))

[4.         0.84147098 3.        ]


Python intuition for Jaacobian

In [34]:
import autograd.numpy as np
from autograd import grad

gradient of a scalar function

In [35]:
def f(x):
    return x[0]**2 + 3*x[1]**2

In [36]:
grad_f=grad(f)

In [37]:
x=np.array([2.0, -1.0])

In [38]:
print(grad_f(x))

[ 4. -6.]


jacobian of a vector function

In [39]:
from autograd import jacobian

In [43]:
def g(x):
    return np.array([
        x[0]**2 + x[1],
        np.sin(x[0])+x[1]**3
    ])


In [44]:
jg=jacobian(g)
print(jg(np.array([1.0, 2.0])))


[[ 2.          1.        ]
 [ 0.54030231 12.        ]]
